export const strings = {
  app: {
    name: 'Contactly',
    tagline: 'Your contacts, organized and synced',
  },
  auth: {
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signOut: 'Sign Out',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot Password?',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    continueWithGoogle: 'Continue with Google',
    magicLinkSent: 'Check your email for a sign-in link',
    resendLink: 'Resend link',
  },
  contacts: {
    title: 'Contacts',
    allContacts: 'All contacts',
    favorites: 'Favourites',
    searchPlaceholder: 'Search contacts',
    noContacts: 'No contacts found',
    noContactsMessage: 'Add your first contact to get started',
    addContact: 'Add Contact',
    editContact: 'Edit Contact',
    deleteContact: 'Delete Contact',
    shareContact: 'Share Contact',
    phoneNumbers: 'Phone Numbers',
    emails: 'Email Addresses',
    address: 'Address',
    notes: 'Notes',
    categories: 'Categories',
    company: 'Company',
    designation: 'Designation',
    lastVisit: 'Last Visit',
  },
  filters: {
    all: 'All',
    staff: 'Staff',
    company: 'Company',
    shared: 'Shared',
    recent: 'Recent',
  },
  actions: {
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    share: 'Share',
    call: 'Call',
    message: 'Message',
    email: 'Email',
    sync: 'Sync',
    import: 'Import',
    export: 'Export',
    merge: 'Merge',
  },
  errors: {
    generic: 'Something went wrong',
    network: 'Network error. Please check your connection.',
    notFound: 'Not found',
    unauthorized: 'Unauthorized',
    validation: 'Please check your input',
    emailRequired: 'Email is required',
    emailInvalid: 'Please enter a valid email',
    nameRequired: 'Name is required',
  },
  success: {
    saved: 'Saved successfully',
    deleted: 'Deleted successfully',
    synced: 'Synced successfully',
  },
  loading: {
    loading: 'Loading...',
    syncing: 'Syncing...',
    saving: 'Saving...',
  },
} as const;

